DIAM_Projeto/DIAM_Projeto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

DIAM_Projeto/home/urls.py
from django.urls import include, path
from . import views
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    # ex: home/
    path('', views.index, name='index'),

    # ex: home/login_view/
    path('login/', views.login_view, name='login'),

    # ex: home/registration
    path('register/', views.register, name='register'),

    # ex: home/new_post/
    path('new_post/', views.new_post, name='new_post'),

    # ex: home/logout
    path('logout/', views.user_logout, name='logout'),

    # ex: home/profile
    path('profile/', views.profile, name='profile'),

    path('<int:post_id>/like/', views.like, name='like'),

    path('<int:post_id>/write_comment', views.write_comment, name='write_comment'),

    path('profile/delete/<int:post_id>/', views.delete_post, name='delete_post'),

    path('not_logged_error/', TemplateView.as_view(template_name='home/not_logged_error.html'),
         name='not_logged_error'),

    path('<int:post_id>/save_favorite/', views.save_favorite, name='save_favorite'),

    path('my_groups', views.my_groups, name='my_groups'),

    path('my_groups/create_group', views.create_group, name='create_group'),

    path('my_groups/group_detail/<int:group_id>/', views.group_detail, name='group_detail'),

    path('my_groups/group_detail/delete_group/<int:group_id>/', views.delete_group, name='delete_group'),

    path('my_groups/group_detail/<int:group_id>/add_group_member/', views.add_group_member, name='add_group_member'),

    path('my_groups/group_detail/<int:group_id>/delete_member/', views.delete_member, name='delete_member'),

    path('my_groups/group_detail/<int:group_id>/new_group_post/', views.new_group_post, name='new_group_post'),

]

DIAM_Projeto/home/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from django.db import models
from django.utils import timezone

import datetime

User = get_user_model()


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    post_content = models.TextField()
    post_time = models.DateTimeField('post date')
    post_title = models.CharField(max_length=100, default='No title')
    liked_by = models.ManyToManyField(User, related_name='post_likes')
    likes_count = models.PositiveIntegerField(default=0)
    topic = models.CharField(max_length=100, null=True)
    favorited_by = models.ManyToManyField(User, related_name='favorite_posts')

    def __str__(self):
        return self.post_content


    def is_recent_publish(self):
        return self.post_time >= timezone.now() - datetime.timedelta(days=1)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    post_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.post.post_title}"




class Group(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='group_members',blank=True)
    group_name = models.CharField(max_length = 50)


class GroupPost(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    group = models.OneToOneField(Group, on_delete=models.CASCADE)

DIAM_Projeto/home/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from django.db.models import Q

from .models import Post, Comment, Like, Group, GroupPost


# Create your views here.
from django.db.models import Count


def index(request):
    order_by = request.GET.get('order_by', 'time')  # Get the 'order_by' query parameter from the request

    if order_by == 'likes':
        latest_post_list = Post.objects.order_by('-likes_count', '-post_time')[:5]
    else:
        latest_post_list = Post.objects.order_by('-post_time')[:5]

    context = {
        'latest_post_list': latest_post_list,
        'order_by': order_by,
    }
    return render(request, 'home/index.html', context)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to success page or some other URL TODO
            return HttpResponseRedirect(reverse('home:index'))
        else:
            # Return invalid an invalid login message
            return render(request, 'home/login.html', {'error': 'Invalid login credentials.'})
    else:
        return render(request, 'home/login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']

        # Check if password matches
        if confirm_password != password:
            return render(request, 'home/register.html', {'error': 'Password does not match.'})

        # Create the user
        try:
            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
        except:
            return render(request, 'home/register.html', {'error': 'Failed to register'})

        # If success
        return HttpResponseRedirect(reverse('home:index'))

    else:
        return render(request, 'home/register.html')


@login_required
def new_post(request):
    context = {'request': request}
    if request.method == 'POST':
        post_title = request.POST['post_title']
        post_content = request.POST['new_post']
        post_time = timezone.now()
        topic = request.POST['topic']
        post_new = Post(post_content=post_content, post_time=post_time, author=request.user,
                        post_title=post_title, topic=topic)
        post_new.save()
        return HttpResponseRedirect(reverse('home:index'))
    else:
        return render(request, 'home/new_post.html', context)


@login_required
def user_logout(request):
    logout(request)
    return redirect('home:index')


@login_required
def profile(request):
    user = request.user
    posts = Post.objects.filter(author=user)
    favorite_posts = user.favorite_posts.all()  # Fetch the user's favorite posts
    return render(request, 'home/profile.html', {'user': user, 'posts': posts, 'favorite_posts': favorite_posts})


def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    liked_post = Like.objects.filter(post=post, user=user).first()
    if not liked_post:
        like_post = Like(post=post, user=user)
        like_post.save()
        post.likes_count += 1
        post.save()
    return redirect('home:index')


@login_required
def write_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == 'POST':
        comment_text = request.POST['comment_text']
        user = request.user  # Retrieve the authenticated user

        # Create a new comment instance
        post_time = timezone.now()
        comment = Comment(post=post, user=user, comment_text=comment_text, post_time=post_time)
        comment.save()

        # Redirect to the post details page or any other desired page
        return redirect('home:index')

    return render(request, 'home/write_comment.html', {'post': post})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:  # Check if the post belongs to the logged-in user
        post.delete()
    return redirect('home:profile')


@login_required
def save_favorite(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user

    if user.favorite_posts.filter(pk=post_id).exists():
        # Post is already a favorite, remove it from favorites
        user.favorite_posts.remove(post)
    else:
        # Post is not a favorite, add it to favorites
        user.favorite_posts.add(post)

    return redirect('home:index')



@login_required
def create_group(request):
    if request.method == 'POST':
        new_group_name = request.POST.get('group_name')
        if Group.objects.filter(group_name=new_group_name).exists():
            messages.error(request,"A group with that name already exists")
            return render(request, 'home/create_group.html')
        new_admin = request.user
        group_new = Group(admin=new_admin, group_name=new_group_name)
        group_new.save()
        messages.success(request,'Group created successfully!')
        return render(request,'home/group_detail.html',{'group': group_new})
    return render(request,'home/create_group.html')

@login_required
def add_group_member(request, group_id):
    context = {'request': request}
    if request.method == 'POST':
        group_member = request.POST['new_group_member']
        try:
            user = get_object_or_404(User, username=group_member)
        except Http404:
            error_msg = f"No user with username '{group_member}' was found."
            context['error'] = error_msg
            return redirect('home:group_detail', group_id=group_id)
        group = Group.objects.get(id=group_id)
        if user not in group.members.all():
            group.members.add(user)
            group.save()
            return redirect('home:my_groups')
        else:
            return render(request, 'home/add_group_member.html', {'group_id': group_id})
    else:
        return render(request, 'home/add_group_member.html', {'group_id': group_id})

@login_required
def group_detail(request, group_id):
    latest_post_list = GroupPost.objects.filter(group_id=group_id)
    group = get_object_or_404(Group,id=group_id)
    return render(request,'home/group_detail.html', {'group':group,'latest_post_list': latest_post_list})

@login_required
def my_groups(request):
    user = request.user
    groups = Group.objects.filter(Q(admin=user) | Q(members=user))
    print(groups)
    return render(request, 'home/my_groups.html', {'groups':groups})

@login_required
def delete_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.admin == request.user:  # Check if the group belongs to the logged-in user
        group.delete()
    return redirect('home:my_groups')

@login_required
def delete_member(request, group_id):
    group = get_object_or_404(Group,pk=group_id)
    if request.method=='POST':
        member_username = request.POST['group_member']
        user = get_object_or_404(User,username=member_username)
        group.members.remove(user.id)
        return redirect('home:group_detail',group_id=group_id)
    return render(request,'home/delete_member.html', {'group_id': group_id})

@login_required
def new_group_post(request, group_id):
    if request.method == 'POST':
        post_title = request.POST['post_title']
        post_content = request.POST['post_content']
        topic = request.POST['topic']
        group = Group.objects.get(id=group_id)

        # Check if the user is a member of the group
        if request.user not in group.members.all() and request.user != group.admin:
            return HttpResponseForbidden("You are not a member of this group.")

        # Create a new Post instance
        post = Post.objects.create(
            author=request.user,
            post_title=post_title,
            post_content=post_content,
            post_time=timezone.now(),
            topic=topic
        )

        # Create a new GroupPost instance and associate it with the group and post
        group_post = GroupPost.objects.create(
            group=group,
            post=post
        )

        return redirect('home:group_detail', group_id=group_id)
    else:
        # Handle GET request for displaying the form
        return render(request, 'home/new_group_post.html', {'group_id': group_id})

DIAM_Projeto/home/templates/home/add_group_member.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Member</title>
      <style>
    h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>

<div class="form-container">
     <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
  <h2>Add Member to {{ group.group_name }}</h2>

  <form action="{% url 'home:add_group_member' group_id=group_id %}" method="post">
  {% csrf_token %}

  <label for="new_group_member">New Member Username:</label><br>
  <input type="text" id="new_group_member" name="new_group_member" required>
  <br><br>

  <button class="button-34" type="submit">Submit</button>
</form>
</div>
<br>
    <button class="button-34" onclick="window.location.href='{% url 'home:group_detail' group_id %}'">Cancel</button>
</body>
</html>

DIAM_Projeto/home/templates/home/create_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Groups</title>
      <style>
    h1,h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
    <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>

    <h2>Create Group</h2>

  <form action="{% url 'home:create_group' %}" method="post">
  {% csrf_token %}

  <label for="group_name">Group Name:</label><br>
  <input type="text" id="group_name" name="group_name" required>


  <button class="button-34" type="submit">Submit</button>
</form>
</div>
    <button class="button-34" onclick="window.location.href='{% url 'home:my_groups' %}'">Cancel</button>
</body>
</html>
</body>
</html>

DIAM_Projeto/home/templates/home/delete_member.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Remove Member</title>
      <style>
    h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
 <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>

<div class="form-container">
  <h2>Remove Member From {{ group.group_name }}</h2>

  <form action="{% url 'home:delete_member' group_id=group_id %}" method="post">
  {% csrf_token %}

  <label for="group_member">Member Username to Delete:</label><br>
  <input type="text" id="group_member" name="group_member" required>
  <br><br>

  <button class="button-34" type="submit">Submit</button>
</form>
</div>
<br>
    <button class="button-34" onclick="window.location.href='{% url 'home:group_detail' group_id %}'">Cancel</button>
</body>
</html>

DIAM_Projeto/home/templates/home/group_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group detail</title>

    <style>
    h2,h3 {
      color: #5E5DF0;
    }
  </style>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css'  %}">
</head>
<body>
    <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>

    <h2>Group details</h2>

    <h3>{{ group.group_name }}</h3>
    <br>
    <button class="button-34" onclick="window.location.href='{% url 'home:new_group_post' group.id %}'">New Group Post</button>
    <br>
    <h3>Admin: {{ group.admin }}</h3>

    <br>
    <h3>Members:</h3>
    <ul>
        {% for member in group.members.all %}
            <li>{{ member.username }}</li>
        <br>
        {% empty %}
            <li>Your group has no members.</li>
        {% endfor %}
    </ul>

    <h3>Group Posts:</h3>
    <ul>
        {% for grouppost in latest_post_list %}
            <li>
                <h4>{{ grouppost.post.post_title }}</h4>
                <p>{{ grouppost.post.post_content }}</p>
            </li>
        {% empty %}
            <li>No posts in this group yet.</li>
        {% endfor %}
    </ul>

      {% if request.user == group.admin %}

    <button class="button-34"  onclick="window.location.href='{% url 'home:add_group_member' group.id %}'">Add New Group Member</button>
    <br>
    <br>

    <button class="button-33" onclick="window.location.href='{% url 'home:delete_member' group.id %}'">Remove Group Member</button>
    <br>
    <br>
    <button class="button-33" onclick="window.location.href='{% url 'home:delete_group' group.id %}'">Delete Group</button>
    {% endif %}
    <button class="button-34" onclick="window.location.href='{% url 'home:my_groups' %}'">Back</button>

</body>
</html>
</body>
</html>

DIAM_Projeto/home/templates/home/groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups</title>
</head>
<body>
    <h1>ISCTFlow</h1>

    <h2>Groups you belong to : </h2>

    <button onclick="window.location.href='{% url 'home:index' %}'">Back</button>
    <button onclick="window.location.href='{% url 'home:create_group' %}'">Create Group</button>
</body>
</html>

DIAM_Projeto/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
      <style>
    h1 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css'  %}">

</head>

<body>

        <div class="navbar">

            <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="500" height="150">
        </a>

            {% if user.is_authenticated %}
                <section class="user-info">
                    Welcome, <a href="{% url 'home:profile' %}">{{ user.username }}</a>!
                    <a href="{% url 'home:logout' %}">Logout</a>
                </section>
            {% else %}
                <button class="button-34" onclick="window.location.href='{% url 'home:login' %}'">Login</button>
                <button class="button-34" onclick="window.location.href='{% url 'home:register' %}'">Register</button>
            {% endif %}
        </div>


        <div class="filter">
            {% if user.is_authenticated %}
            <button class="button-35" onclick="window.location.href='{% url 'home:my_groups' %}'">Groups</button>
                <button class="button-35" onclick="window.location.href='{% url 'home:new_post' %}'">New Post</button>
            {% endif %}

            {% if latest_post_list %}
                <form method="get" action="{% url 'home:index' %}">
                    <label for="order_by">Order By:</label>
                    <select id="order_by" name="order_by">
                        <option value="time" {% if order_by == 'time' %}selected{% endif %}>Most Recent</option>
                        <option value="likes" {% if order_by == 'likes' %}selected{% endif %}>Likes</option>
                    </select>

                    <button class="button-35" type="submit">Apply</button>
                </form>
        </div>

{% for post in latest_post_list %}

        <div class="post">
            <section class="post_tittle">
                <h2> {{ post.post_title }} </h2>
            </section>

            <section class="post_content">
                <p>{{ post.post_content }} </p>
            </section>

            <section class="actions_post">
                Likes: {{ post.likes_count }}

                 {% if user.is_authenticated %}
                    <form method="post" action="{% url 'home:like' post.id %}">
                        {% csrf_token %}
                        <button class="button-34" type="submit">Like</button>
                    </form>
                    <a href="{% url 'home:write_comment' post.id %}">Write Comment</a>
                {% else %}
                    <a href="{% url 'home:not_logged_error' %}">Write Comment</a>
                {% endif %}

                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'home:save_favorite' post.id %}">
                        {% csrf_token %}
                        {% if post in user.favorite_posts.all %}
                            <button class="button-34" type="submit" name="action" value="remove">Remove from Favorites</button>
                        {% else %}
                            <button class="button-34" type="submit" name="action" value="save">Save as Favorite</button>
                        {% endif %}
                    </form>
                {% endif %}
            </section>
        </div>
        <div class="comment-section">
       <h3>Comments:</h3>

       {% for comment in post.comment_set.all %}

            <p>{{ comment.comment_text }}</p>

       {% empty %}
            <p>No comments yet.</p>
       {% endfor %}
        </div>
        </p>
    {% endfor %}



{% else %}
<p>Nao ha publicacoes</p>
{% endif %}


</body>
</html>

DIAM_Projeto/home/templates/home/my_groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups</title>
      <style>
    h1,h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
     <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>

    <h2>Groups you belong to : </h2>

    <ul>
        {% for group in groups %}
            <li><a href="{% url 'home:group_detail' group.id %}">{{ group.group_name }}</a></li>
        {% empty %}
            <li>You don't belong to any group.</li>
        {% endfor %}
    </ul>

    <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Back</button>
    <button class="button-34" onclick="window.location.href='{% url 'home:create_group' %}'">Create Group</button>
</body>
</html>

DIAM_Projeto/home/templates/home/new_group_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Group Post</title>
      <style>
    h1,h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
<div class="form-container">
   <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
  <h2>Create Group Post</h2>

  <form action="{% url 'home:new_group_post' group_id %}" method="post">
    {% csrf_token %}

    <label for="post_title">Post Title:</label><br>
    <input type="text" id="post_title" name="post_title" required>
    <br><br>

    <label for="post_content">New Group Post:</label><br>
    <textarea id="post_content" name="post_content" rows="4" cols="50" placeholder="Write your post here..."></textarea>
    <br><br>

    <label for="topic">Topic:</label>
    <select id="topic" name="topic">
      <option value="java">Java</option>
      <option value="python">Python</option>
      <option value="html">HTML</option>
      <option value="other">Other</option>
    </select>

    <br><br>

    <button class="button-34" type="submit">Submit</button>
  </form>
</div>
<br>
    <button class="button-34" onclick="window.location.href='{% url 'home:group_detail' group_id %}'">Cancel</button>
</body>
</html>

DIAM_Projeto/home/templates/home/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
 <style>
    h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">


</head>
<body>
 <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
<div class="form-container">
  <h2>Create Post</h2>

  <form action="{% url 'home:new_post' %}" method="post">
  {% csrf_token %}

  <label for="post_title">Post Title:</label><br>
  <input type="text" id="post_title" name="post_title" required>
  <br><br>

  <label for="new_post">New Post:</label><br>
  <textarea id="new_post" name="new_post" rows="4" cols="50" placeholder="Write your post here..."></textarea>
  <br><br>

  <label for="topic">Topic:</label>
      <select id="topic" name="topic">
        <option value="java">Java</option>
        <option value="python">Python</option>
        <option value="html">HTML</option>
        <option value="other">Other</option>
      </select>

  <br><br>

  <button class="button-34" type="submit">Submit</button>
</form>
</div>
<br>
    <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Cancel</button>
</body>
</html>

DIAM_Projeto/home/templates/home/not_logged_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not Logged In</title>
      <style>
    h1 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
     <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
    <br>
     <br>
    <a>You are not logged in, if you want to be able to make comments and likes you need to log in</a>

    <br>
    <a>If you do not have an account you can also create one for free</a>
<br>
    <br>
    <button class="button-34" onclick="window.location.href='{% url 'home:login' %}'">Login</button>
    <br>
    <br>
    <button class="button-34" onclick="window.location.href='{% url 'home:register' %}'">Register</button>
    <br>
<br>
    <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Back</button>
</body>
</html>

DIAM_Projeto/home/templates/home/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
     <style>
    h1,h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">

</head>
<body>
 <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
 <h1>User Details</h1>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
<section class="actions_post2">
 <h2>Posts:</h2>
    {% if posts %}
    <ul>

        {% for post in posts %}
            <li>

                {{ post.post_content }}
                <form method="post" action="{% url 'home:delete_post' post.id %}">
                    {% csrf_token %}
                    <button class="button-33" type="submit">Delete</button>
                    <br>
                </form>

            </li>
        {% endfor %}

    </ul>

{% else %}
    <p>No posts available.</p>
{% endif %}
</section>
<br>

 <h2>Favorite:</h2>
{% if favorite_posts %}
        <ul>
            {% for post in favorite_posts %}
                <li>
                    {{ post.post_content }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No favorite posts available.</p>
    {% endif %}

 <br>

   <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Back</button>
</body>
</html>

DIAM_Projeto/home/templates/home/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    <style>
     h1 {
      color: #5E5DF0;
    }
  </style>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
 <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
    <h1>Registration</h1>
    <form method="POST" action="{% url 'home:register' %}">
        {% csrf_token %}
        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>
            <br>
        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
            <br>
        <div>
            <label for="confirm_password">Confirm Password:</label>
            <input type="password" id="confirm_password" name="confirm_password" required>
        </div>
<br>
        <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email">
        </div>
        <br>
        <button class="button-34" type="submit">Register</button>
    </form>
    <br>
    <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Back</button>
</body>
</html>

DIAM_Projeto/home/templates/home/write_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Write Comment</title>
      <style>
    h1,h2 {
      color: #5E5DF0;
    }
  </style>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
</head>
<body>
 <a href="/home">
        <img src="{% static 'home/images/image.png'%}" alt="ISCTEFLOW" width="400" height="100">
        </a>
  <h1>Write Comment</h1>

    <h2>Post:</h2>
    <p>{{ post.post_content }}</p>

    <h2>Write your comment:</h2>

    <form method="post" action="{% url 'home:write_comment' post.id %}">
        {% csrf_token %}
        <textarea name="comment_text" rows="4" cols="50"></textarea>
        <br>
        <input class="button-34" type="submit" value="Submit Comment">
    </form>
    <br>
    <button class="button-34" onclick="window.location.href='{% url 'home:index' %}'">Back</button>
</body>
</html>